name: Build

on: 
  push:
    branches: 
      - master
      - build_test

jobs:

  Build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Install pyinstaller
      run: |
        pip install wheel
        git clone https://github.com/pyinstaller/pyinstaller.git
        cd pyinstaller/bootloader
        python ./waf all --target-arch=64bit
        cd ..
        python setup.py install
      working-directory: c:/
    
    - name: Build with pyinstaller
      run: 
        pyinstaller build_github.spec
    
    - uses: actions/upload-artifact@v1
      with:
        name: DownloaderForReddit_${{ github.run_number }}
        path: dist/DownloaderForReddit